name: Build Docker image and Scan using snyk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Scan image
        continue-on-error: true
        run: snyk container test myapp:latest --file=Dockerfile

      - name: Generate report
        continue-on-error: true
        run: snyk container test myapp:latest --file=Dockerfile --json > snyk-report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
